# Markdownlint configuration
# See: https://github.com/DavidAnson/markdownlint

default: true

# MD013: Line length
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: false
  tables: false
  headings: true
  strict: false

# MD033: Inline HTML
MD033:
  allowed_elements:
    - br
    - details
    - summary

# MD041: First line in file should be a top-level heading
MD041: false

# MD046: Code block style
MD046:
  style: fenced
